#pragma once

#include "common_sys.h"

#define RCC_BASE 0x58024400U

#define RCC_BDCR REG32((RCC_BASE) + 0x70)

#define RCC_BDCR_BDRST (1 << 16)
#define RCC_BDCR_RTCEN (1 << 15)
#define RCC_BDCR_RTCSEL_MASK 0x3
#define RCC_BDCR_RTCSEL_SHIFT 8
#define RCC_BDCR_RTCSEL_NONE 0
#define RCC_BDCR_RTCSEL_LSE 1
#define RCC_BDCR_RTCSEL_LSI 2
#define RCC_BDCR_RTCSEL_HSE 3
#define RCC_BDCR_LSEDRV_MASK 0x3
#define RCC_BDCR_LSEDRV_SHIFT 3
#define RCC_BDCR_LSEDRV_LOW 0
#define RCC_BDCR_LSEDRV_MEDH 1
#define RCC_BDCR_LSEDRV_MEDL 2
#define RCC_BDCR_LSEDRV_HIGH 3
#define RCC_BDCR_LSEBYP (1 << 2)
#define RCC_BDCR_LSERDY (1 << 1)
#define RCC_BDCR_LSEON (1 << 0)

#define RCC_RTC_CLKSOURCE_LSE (RCC_BDCR_RTCSEL_LSE)

#define POWER_CONTROL_BASE 0x58024800U

#define PWR_CR1 REG32(POWER_CONTROL_BASE + 0x00)

#define PWR_CR1_DBP (1 << 8)

#define RTC_BASE 0x58004000U

#define RTC_BKP_BASE (RTC_BASE + 0x50)
#define BKP0R RTC_BKP_BASE

#define RTC_BKP_DR0 0x00000000U
#define RTC_BKP_DR1 0x00000001U
#define RTC_BKP_DR2 0x00000002U
#define RTC_BKP_DR3 0x00000003U

#define RTC_BKP_DR0_VAL 0xA5A5A5A5U

#define RTC_WRITE_PROTECTION_ENABLE 0xFFU
#define RTC_WRITE_PROTECTION_DISABLE_1 0xCAU
#define RTC_WRITE_PROTECTION_DISABLE_2 0x53U

#define RTC_WPR REG32(RTC_BASE + 0x24)

#define RTC_ISR REG32(RTC_BASE + 0x0c)

#define RTC_ISR_RSF (1 << 5)
#define RTC_ISR_INITF (1 << 6)
#define RTC_ISR_INIT (1 << 7)
#define RTC_INIT_MASK 0xFFFFFFFF

#define RTC_CR REG32(RTC_BASE + 0x08)

#define RTC_CR_BYPSHAD (1 << 5)
#define RTC_CR_FMT (1 << 6)
#define RTC_CR_FMT_SHIFT 6

#define RTC_HOURFORMAT_24HOUR 0
#define RTC_HOURFORMAT_AMPM 1

#define RTC_ASYNCH_PRESCALER 31
#define RTC_SYNCH_PRESCALER 1023

#define RTC_PRER REG32(RTC_BASE + 0x10)

#define RTC_PRER_PREDIV_A_SHIFT 16
#define RTC_PRER_PREDIV_A_MASK 0x7f
#define RTC_PRER_PREDIV_S_SHIFT 0
#define RTC_PRER_PREDIV_S_MASK 0x7fff

#define RTC_TR REG32(RTC_BASE + 0x00)
#define RTC_DR REG32(RTC_BASE + 0x04)

#define RTC_FORMAT_BIN 0x00000000U
#define RTC_FORMAT_BCD 0x00000001U

#define RTC_TR_PM_SHIFT 22
#define RTC_TR_PM 1
#define RTC_TR_HT_SHIFT 20
#define RTC_TR_HT_MASK 0x3
#define RTC_TR_HU_SHIFT 16
#define RTC_TR_HU_MASK 0xf
#define RTC_TR_MNT_SHIFT 12
#define RTC_TR_MNT_MASK 0x7
#define RTC_TR_MNU_SHIFT 8
#define RTC_TR_MNU_MASK 0xf
#define RTC_TR_ST_SHIFT 4
#define RTC_TR_ST_MASK 0x7
#define RTC_TR_SU_SHIFT 0
#define RTC_TR_SU_MASK 0xf

#define RTC_DR_YT_SHIFT 20
#define RTC_DR_YT_MASK 0xf
#define RTC_DR_YU_SHIFT 16
#define RTC_DR_YU_MASK 0xf
#define RTC_DR_WDU_SHIFT 13
#define RTC_DR_WDU_MASK 0x7
#define RTC_DR_MT_SHIFT 12
#define RTC_DR_MT_MASK 1
#define RTC_DR_MU_SHIFT 8
#define RTC_DR_MU_MASK 0xf
#define RTC_DR_DT_SHIFT 4
#define RTC_DR_DT_MASK 0x3
#define RTC_DR_DU_SHIFT 0
#define RTC_DR_DU_MASK 0xf

#define RTC_SSR REG32(RTC_BASE + 0x28)
